name: fitness_storm
description: A new Flutter project.

publish_to: 'none'

version: 1.1.38+68

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter


  table_calendar: ^3.1.2
  dio: ^5.7.0
  group_button: ^5.3.4
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  package_info_plus: ^8.0.3
  pod_player:
    path: pod_player
  readmore: ^3.0.0
  wakelock_plus: ^1.2.8
  google_sign_in: ^6.2.1
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1

  #### start Firebase #########
  firebase_auth: ^5.3.1
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  #### end Firebase #########

  get: ^4.6.6
  logger: ^2.4.0
  pull_to_refresh: ^2.0.0
  pinput: ^5.0.0
  screen_protector: ^1.4.2+1
  lottie: ^3.1.2
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.3
  adaptive_scrollbar: ^2.1.2
  flutter_local_notifications: ^17.2.3
  quiver: ^3.2.2
  webview_flutter: ^4.9.0

  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  image_picker: ^1.1.2
  mime: ^1.0.6
  collection: ^1.18.0
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  #  flutter_meta_sdk: ^1.0.2
  intl_phone_number_input: ^0.7.4
  flutter_inappwebview: ^6.1.5


  #---------------- saed ----------------------

  #  flutter_background_service: ^5.0.5
  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android

  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type

  m_cubit:
    git:
      url: https://github.com/saedAlHanash/m_cubit
  #  m_cubit:
  #    path: ../../packages/m_cubit

  cupertino_icons: ^1.0.8
  day_night_time_picker: ^1.3.1
  equatable: ^2.0.5
  syncfusion_flutter_datepicker: ^27.1.52
  get_it: ^8.0.0
  internet_connection_checker:
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  dropdown_button2: ^2.3.9
  awesome_dialog: ^3.2.1
  flutter_rating_bar: ^4.0.1
  flutter_cached_pdfview: ^0.4.2
#  linkfy_text: ^1.1.6
  fluttertoast: ^8.2.8
  win32: ^5.5.5
  archive: ^3.6.1
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
#  appsflyer_sdk: ^6.14.3
#  ------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  dependency_validator:
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
    - family: semeBold
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf

flutter_intl:
  enabled: true





