name: fitness_storm
description: A new Flutter project.

publish_to: 'none'

version: 1.1.26+52

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  hive_flutter: any
  table_calendar: ^3.0.9
  smooth_page_indicator: ^1.0.0+2
  dio:
  group_button:
#  flutter_holo_date_picker: ^1.0.3
  badges:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.1
  intl: any
  package_info_plus: ^4.2.0
  bottom_picker: ^1.8.1
  pod_player:
    path: pod_player
  readmore: ^2.2.0
  wakelock_plus: ^1.1.4
  #  flutter_native_splash: ^2.2.5
  google_sign_in:
#  agora_rtc_engine: ^6.3.1
  permission_handler:
  flutter_app_badger:
  firebase_auth: ^5.1.2
  firebase_analytics: ^11.2.0
  firebase_dynamic_links: ^6.0.3
  get: ^4.6.6
  get_storage: ^2.0.3
  logger: ^2.0.2+1
  pull_to_refresh: ^2.0.0
  awesome_icons: ^1.1.0
  pinput: ^2.2.31
  screen_protector: ^1.2.0
  lottie: ^1.4.1
  scroll_snap_list: ^0.9.1
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.5
  percent_indicator: ^4.2.2
  adaptive_scrollbar: ^2.1.2
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0
  flutter_local_notifications: ^17.1.1
  cached_network_image: ^3.3.1
  quiver: ^3.1.0
  webview_flutter: ^3.0.4
  sliding_up_panel:
  shared_preferences: ^2.1.0
  file_picker:
  firebase_storage: ^12.1.1
  flutter_chat_types: ^3.6.1
  cloud_firestore: ^5.1.0
  flutter_chat_ui: ^1.6.14
#  flutter_firebase_chat_core: ^1.6.7
  image_picker:
  mime: ^1.0.4
  collection: any
  open_filex: ^4.3.2
  path_provider:
  shimmer_animation: ^2.1.0+1
  flutter_meta_sdk: ^1.0.2
  intl_phone_number_input:
  flutter_inappwebview:
#  agora_uikit: ^1.3.10
  vimeo_player_flutter:
  dart_jsonwebtoken:
  #---------------- saed ----------------------

#  flutter_background_service: ^5.0.5
  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android

  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type

  cupertino_icons: ^1.0.2
  day_night_time_picker: ^1.3.0+1
  #  device_info_plus: ^9.1.1
  equatable: ^2.0.5
  syncfusion_flutter_datepicker:
  get_it: ^7.6.6
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.0
  flutter_screenutil: ^5.9.0
  dropdown_button2: ^2.3.9
  awesome_dialog: ^3.2.0
  flutter_rating_bar:
  flutter_cached_pdfview: ^0.4.2
  linkfy_text: ^1.1.6
  appsflyer_sdk: ^6.14.3
#  ------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  dependency_validator:
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - asset/Images/
    - asset/lotties/

  fonts:
    - family: Roboto
      fonts:
        - asset: asset/Font/Roboto-Regular.ttf
        - asset: asset/Font/Roboto-Bold.ttf
          weight: 700
        - asset: asset/Font/Roboto-Italic.ttf
          style: italic

        - asset: asset/Font/Roboto-Medium.ttf
          weight: 300

    - family: roboto
      fonts:
        - asset: asset/Font/Roboto-Regular.ttf
    - family: robotoSimBold
      fonts:
        - asset: asset/Font/Roboto-Medium.ttf
    - family: robotoBold
      fonts:
        - asset: asset/Font/Roboto-Bold.ttf
flutter_intl:
  enabled: true






