// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQNJPPpwccWSWZuBk-8IJsBcIuMMkuxX8',
    appId: '1:644714333877:android:569d4dcdd048a372b820fc',
    messagingSenderId: '644714333877',
    projectId: 'fitness-strom-1',
    storageBucket: 'fitness-strom-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg6BBIOzBi4B5LuSjh1sBO34uTOhzbjco',
    appId: '1:644714333877:ios:576cca000fca062cb820fc',
    messagingSenderId: '644714333877',
    projectId: 'fitness-strom-1',
    storageBucket: 'fitness-strom-1.appspot.com',
    androidClientId: '644714333877-46uebmts9jf82k8r33e21oc4jltai9d7.apps.googleusercontent.com',
    iosClientId: '644714333877-120vrkjeaqnlmihnacereairhcv9i2ih.apps.googleusercontent.com',
    iosBundleId: 'com.chi.fitnessStorm',
  );
}
